Print the complete error when fails
kubernetes-sigs/e2e-framework pull request #360
Opened 2023-12-06 04:02 UTC by wzshiming

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Clean the rest like #349

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., Usage docs, etc.:

```docs
NONE
```

2023-12-06 23:27 UTC, cpanato approved these changes
/lgtm

2023-12-12 10:22 UTC, harshanarayana requested changes

2023-12-12 10:22 UTC, harshanarayana commented on support/kind/kind.go
> +		return "", fmt.Errorf("failed to create kind %q cluster: %s: %s: %s", k.name, p.Err(), p.Result(), string(outBytes))
```suggestion
		return "", fmt.Errorf("failed to create kind cluster %q: %s: %s: %s", k.name, p.Err(), p.Result(), string(outBytes))
```

might be more readable ?

2023-12-12 10:22 UTC, harshanarayana commented on support/kwok/kwok.go
> +		return "", fmt.Errorf("failed to create kwok %q cluster: %s: %s: %s", k.name, p.Err(), p.Result(), string(outBytes))
Same as above.

2023-12-12 10:22 UTC, harshanarayana commented on support/kind/kind.go
> +		return fmt.Errorf("kind: delete cluster %q cluster: %s: %s: %s", k.name, p.Err(), p.Result(), string(outBytes))
```suggestion
		return fmt.Errorf("kind: delete cluster %q: %s: %s: %s", k.name, p.Err(), p.Result(), string(outBytes))
```

2023-12-12 10:22 UTC, harshanarayana commented on support/kwok/kwok.go
> +		return fmt.Errorf("kwok: delete cluster %q cluster: %s: %s: %s", k.name, p.Err(), p.Result(), string(outBytes))
```suggestion
		return fmt.Errorf("kwok: delete cluster %q: %s: %s: %s", k.name, p.Err(), p.Result(), string(outBytes))
```

2023-12-12 10:40 UTC, wzshiming commented
Done

2023-12-19 15:49 UTC, vladimirvivien approved these changes
/lgtm

2023-12-19 15:54 UTC, merged